Task-53511: character counter and date picker are not correctly positioned
exo-addons/lead-capture pull request #37
Opened 2022-02-28 13:58 UTC by wassimmhamdi

Problem: the character counter and the dater picker are not correctly positioned that makes a problem in the start / due date remove
Fix: in the **main.less** file of the lead-capture addons I rename the two classes **DrawerContent** and **TaskDrawer** to make sure that they are not duplicated from an other file

2022-03-01 09:04 UTC, rdenarie requested changes

2022-03-01 09:04 UTC, rdenarie commented on war/src/main/webapp/css/main.less
> +        }
```suggestion
        }    
```

2022-03-01 09:13 UTC, rdenarie requested changes
Can you confirm that you test apps leadsManagement, mailTemplatesManagement, leadCaptureSettings, resourcesManagement and compaignsManagement, and the css for theses apps is still ok after you modification ?

2022-03-02 10:07 UTC, wassimmhamdi commented
I confirm that I test all of the apps leadsManagement, mailTemplatesManagement, leadCaptureSettings, resourcesManagement and compaignsManagement, with @mkrout and  the css for theses apps is still ok after the modification 
cc @mkrout do you confirm !

2022-03-02 10:13 UTC, rdenarie approved these changes

2022-03-02 10:14 UTC, merged